In [1]:
import numpy as np

In [2]:
!pip freeze | grep numpy

numpy==1.16.4


In [3]:
a = np.random.random((2,3,5))

In [4]:
a

array([[[0.96811821, 0.18465621, 0.18642355, 0.12943184, 0.01096907],
        [0.03958345, 0.27480768, 0.98480495, 0.71595543, 0.29544201],
        [0.73876242, 0.69217786, 0.2454784 , 0.00453268, 0.96250681]],

       [[0.86842066, 0.2701451 , 0.44374498, 0.69375118, 0.05917372],
        [0.90549697, 0.8471278 , 0.49519749, 0.1414773 , 0.49665119],
        [0.43948194, 0.7863733 , 0.33429817, 0.33440718, 0.5883386 ]]])

In [5]:
b = np.ones((5,2,3))

In [6]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
np.shape(a) == np.shape(b)

False

In [8]:
x = np.append (a, b)

In [9]:
x

array([0.96811821, 0.18465621, 0.18642355, 0.12943184, 0.01096907,
       0.03958345, 0.27480768, 0.98480495, 0.71595543, 0.29544201,
       0.73876242, 0.69217786, 0.2454784 , 0.00453268, 0.96250681,
       0.86842066, 0.2701451 , 0.44374498, 0.69375118, 0.05917372,
       0.90549697, 0.8471278 , 0.49519749, 0.1414773 , 0.49665119,
       0.43948194, 0.7863733 , 0.33429817, 0.33440718, 0.5883386 ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [10]:
d = np.append (a, b)

In [11]:
d

array([0.96811821, 0.18465621, 0.18642355, 0.12943184, 0.01096907,
       0.03958345, 0.27480768, 0.98480495, 0.71595543, 0.29544201,
       0.73876242, 0.69217786, 0.2454784 , 0.00453268, 0.96250681,
       0.86842066, 0.2701451 , 0.44374498, 0.69375118, 0.05917372,
       0.90549697, 0.8471278 , 0.49519749, 0.1414773 , 0.49665119,
       0.43948194, 0.7863733 , 0.33429817, 0.33440718, 0.5883386 ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])